import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {css, jsx} from '@emotion/css';

export default function Home() {
  const color = 'white'
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          Ultimate Project

          <div className={css`
            padding: 32px;
            background-color: hotpink;
            font-size: 24px;
            border-radius: 4px;
            &:hover{
              color: ${color}
            }
          `}>
                Hover Over
          <Link href="/register">
            <a>register</a>
          </Link>
          
          <Link href="/login">
            <a>login</a>
          </Link>
          </div>
          
      </main>


     
    </div>
  )
}
