import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { css, jsx } from '@emotion/css'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'
import { Button, InputEmail, InputPassword } from '../components'
import FormControl from '../containers/FormControl/FormControl'
import {useRouter} from 'next/link';

export default function Login() {
  const [formValue, setForm] = useState({})
  const router = useRouter();
  const handleSubmit = (event) => {
    if (event) event.preventDefault()

    console.log('handleSubmit', formValue);
    router.push('/');
  }

  const handleOnChange = (name, value) => {
    setForm({
      ...formValue,
      [name]: value,
    })
  }

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <LayoutAuth>
          <>
            <form onSubmit={handleSubmit}>
              <FormControl>
                <InputEmail
                  onChange={() => handleOnChange('email', value)}
                  placeholder="email"
                />
              </FormControl>
              <FormControl>
                <InputPassword
                  onChange={() => handleOnChange('password', value)}
                  placeholder="password"
                />
              </FormControl>
              <FormControl>
                <Button type="submit">Submit</Button>
              </FormControl>
            </form>
          </>
        </LayoutAuth>
      </main>
    </div>
  )
}
