import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {css, jsx} from '@emotion/css';
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth';
import { Button, InputEmail,InputPassword } from '../components';
import FormControl from '../containers/FormControl/FormControl'

export default function Login() {
  const handleSubmit = (event)=> {
    if(event) event.preventDefault();  
    console.log('handleSubmit');
  }
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
 
            <LayoutAuth>
                <>
                     <form onSubmit={handleSubmit}>
                         <FormControl>
                            <InputEmail placeholder='email' />
                         </FormControl>
                         <FormControl>                        
                            <InputPassword placeholder='password' />
                         </FormControl>
                         <FormControl> 
                            <Button type="submit">Submit</Button>
                         </FormControl> 
                     </form>
                 </>
            </LayoutAuth>
      </main>


     
    </div>
  )
}
